<title>AccuFlow</title>
<META HTTP-EQUIV="Pragma" CONTENT="no-cache">
<META HTTP-EQUIV="Expires" CONTENT="-1">
<meta content="Microsoft Visual Studio 7.0" name=GENERATOR>
<meta content=C# name=CODE_LANGUAGE>
<meta content=JavaScript name=vs_defaultClientScript>
<meta content=http://schemas.microsoft.com/intellisense/ie5 name=vs_targetSchema>

<link rel="stylesheet" href='<%= Request.ApplicationPath + "/Main.css" %>' type="text/css" />
<script src='<%= Request.ApplicationPath + "/Scripts/Main.js" %>' ></script>